#!/usr/bin/env python3
# generate_readme.py
import os
import re
from pathlib import Path

# Use GitHub environment variables when run in Actions
owner_repo = os.environ.get("GITHUB_REPOSITORY", "BillTsigkas/ConvertAdnFetch")
branch = os.environ.get("GITHUB_REF_NAME", "main")

# Files to ignore in the listing
IGNORE = {"whitelist.txt", "changelog.txt", "README.md"}

# Map filenames to nicer display names for special cases
SPECIAL_NAMES = {
    "500px": "500px",
    "9gag": "9GAG",
    "mail_ru": "Mail.ru",
    "4chan": "4chan",
    "ok": "OK",
    "vk": "VK",
    "youtube": "YouTube",
    "tiktok": "TikTok",
    "whatsapp": "WhatsApp",
    "facebook": "Facebook",
    "linkedin": "LinkedIn",
    "pinterest": "Pinterest",
    "reddit": "Reddit",
    "snapchat": "Snapchat",
    "tinder": "Tinder",
    "twitch": "Twitch",
    "twitter": "Twitter",
    "onlyfans": "OnlyFans",
    "bluesky": "Bluesky"
}

def friendly_name(filename):
    name = filename.rsplit('.', 1)[0]
    name = re.sub(r'(_pihole|_asterisk)$', '', name, flags=re.I)
    name = name.strip()
    key = name.lower()
    if key in SPECIAL_NAMES:
        return SPECIAL_NAMES[key]
    return name.replace('_', ' ').title()

def raw_url(filename):
    owner, repo = owner_repo.split('/')
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{filename}"

def main():
    files = sorted([p.name for p in Path('.').glob('*.txt') if p.name not in IGNORE])
    entries = []
    for f in files:
        entries.append((friendly_name(f), raw_url(f)))
    entries.sort(key=lambda x: x[0].lower())
    lines = []
    lines.append("# ConvertAndFetch")
    lines.append("Convert and fetch blocking lists in a format Pi‑hole can read.\n")
    lines.append("## ConvertAndFetch Blocklists\n")
    lines.append("Below are the per-service Pi‑hole blocklists generated by this repository.  ")
    lines.append("Click the **Raw** link to copy the URL and add it to Pi‑hole → Settings → Blocklists.\n")
    lines.append("| **Service** | **Raw link** |")
    lines.append("| --- | --- |")
    for name, url in entries:
        lines.append(f"| **{name}** | [Raw]({url}) |")
    lines.append("\n---\n")
    lines.append("**Tip:** After the workflow runs, open any of the Raw links in your browser, copy the URL, and paste it into Pi‑hole → Settings → Blocklists.")
    Path("README.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote README.md with {len(entries)} entries.")

if __name__ == "__main__":
    main()
