#!/usr/bin/env python3
# generate_readme.py
import os
import re
from pathlib import Path

owner_repo = os.environ.get("GITHUB_REPOSITORY", "BillTsigkas/ConvertAdnFetch")
branch = os.environ.get("GITHUB_REF_NAME", "main")

IGNORE = {"whitelist.txt", "changelog.txt", "README.md"}

SPECIAL_NAMES = {
    "500px": "500px",
    "9gag": "9GAG",
    "mail_ru": "Mail.ru",
    "4chan": "4chan",
    "ok": "OK",
    "vk": "VK",
    "youtube": "YouTube",
    "tiktok": "TikTok",
    "whatsapp": "WhatsApp",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "linkedin": "LinkedIn",
    "pinterest": "Pinterest",
    "reddit": "Reddit",
    "snapchat": "Snapchat",
    "tinder": "Tinder",
    "twitch": "Twitch",
    "twitter": "Twitter",
    "onlyfans": "OnlyFans",
    "bluesky": "Bluesky"
}

def friendly_name(filename):
    # filename may include path like "generated/4chan.txt"
    name = filename.rsplit('/', 1)[-1]
    name = name.rsplit('.', 1)[0]
    name = re.sub(r'(_pihole|_asterisk)$', '', name, flags=re.I)
    key = name.lower()
    if key in SPECIAL_NAMES:
        return SPECIAL_NAMES[key]
    return name.replace('_', ' ').title()

def raw_url(filename):
    owner, repo = owner_repo.split('/')
    filename = filename.lstrip('./')
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{filename}"

def find_txt_files():
    candidates = []
    # search generated/ first, then repo root
    for base in (Path('generated'), Path('.')):
        if not base.exists():
            continue
        for p in base.glob('*.txt'):
            if p.name in IGNORE:
                continue
            candidates.append(str(p).lstrip('./'))
    # also include one-level subfolders if any
    for sub in Path('.').glob('*/'):
        if sub.name in ('.github', 'generated'):
            continue
        for p in sub.glob('*.txt'):
            if p.name in IGNORE:
                continue
            candidates.append(str(p).lstrip('./'))
    # unique and sorted
    unique = sorted(dict.fromkeys(candidates))
    return unique

def main():
    files = find_txt_files()
    entries = [(friendly_name(f), raw_url(f)) for f in files]
    entries.sort(key=lambda x: x[0].lower())
    lines = []
    lines.append("# ConvertAndFetch")
    lines.append("Convert and fetch blocking lists to wildcards in Pihole/AdBlock format.\n")
    lines.append("## ConvertAndFetch Blocklists\n")
    lines.append("Below are the per-service Pi‑hole blocklists generated by this repository.  ")
    lines.append("These lists are not mine and are not maintained by me. These lists are coming from other sources.\n")
    lines.append("Click the **Raw** link to copy the URL and add it to Pi‑hole → Settings → Blocklists. ")
    lines.append("| **Service** | **Raw link** |")
    lines.append("| --- | --- |")
    for name, url in entries:
        lines.append(f"| **{name}** | [Raw]({url}) |")
    lines.append("\n---\n")
    Path("README.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote README.md with {len(entries)} entries.")

if __name__ == "__main__":
    main()
